GET http://localhost:4000/hotel

###

POST http://localhost:4000/hotel
Content-Type: application/json

{
    "hotelname" : "Britannia",
    "description" : "Modest rooms in an unpretentious lodging offering a carvery restaurant, a cosy bar & free Wi-Fi.",
    "linkBook" : "https://www.google.com/travel/hotels/Birmingham/entity/CgoIhcmA5c2dwMtmEAE?g2lb=2502548%2C2503153%2C4254308%2C4258168%2C4260007%2C4270442%2C4271060%2C4274032%2C4291318%2C4305595%2C4306835%2C4308216%2C4314846%2C4317915%2C4328159%2C4329288%2C4330113%2C4338438%2C4348882%2C4270859%2C4284970%2C4291517%2C4292955%2C4316256&hl=en&gl=uk&un=1&q=hotels%20in%20birmingham%20city%20centre&rp=EIHU4oDdn6jnjwEQhcmA5c2dwMtmELbA85aS-NDZDBCTudPktszj7yE4AUAASAI&ictx=1&ved=2ahUKEwjGtNCbm9TnAhWMVBUIHdnLD3kQvS4wAXoECAgQLQ&hrf=CgUIrwEQACIDR0JQKhYKBwjkDxACGBESBwjkDxACGBIYASgAWAGqARoKAgghEgIIDxICCBUSAggNEgIIZxICCC8YAaoBCgoCCBQSAggbGAGqAQ4KAggcEgIIcxICCEcYAaoBCgoCCCUSAgh6GAGqARoKAggREgIIKhICCEASAgg4EgIIVxICCCsYAaoBCwoCCC4SAwiAARgBqgEGCgIIRhgAqgEKCgIIUBICCE8YAaoBBgoCCDkYAJIBAiAB",
    "linkReview" : "https://www.google.com/travel/hotels/Birmingham/entity/CgoIhcmA5c2dwMtmEAE/reviews?g2lb=2502548%2C2503153%2C4254308%2C4258168%2C4260007%2C4270442%2C4271060%2C4274032%2C4291318%2C4305595%2C4306835%2C4308216%2C4314846%2C4317915%2C4328159%2C4329288%2C4330113%2C4338438%2C4348882%2C4270859%2C4284970%2C4291517%2C4292955%2C4316256&hl=en&gl=uk&un=1&q=hotels%20in%20birmingham%20city%20centre&rp=EIHU4oDdn6jnjwEQhcmA5c2dwMtmELbA85aS-NDZDBCTudPktszj7yE4AUAASAI&ictx=1&ved=2ahUKEwjGtNCbm9TnAhWMVBUIHdnLD3kQvS4wAXoECAgQLQ&hrf=CgUIrwEQACIDR0JQKhYKBwjkDxACGBESBwjkDxACGBIYASgAWAGqARoKAgghEgIIDxICCBUSAggNEgIIZxICCC8YAaoBCgoCCBQSAggbGAGqAQ4KAggcEgIIcxICCEcYAaoBCgoCCCUSAgh6GAGqARoKAggREgIIKhICCEASAgg4EgIIVxICCCsYAaoBCwoCCC4SAwiAARgBqgEGCgIIRhgAqgEKCgIIUBICCE8YAaoBBgoCCDkYAJIBAiAB",
    "linkImage": "https://www.britanniahotels.com/image/fit/660x340/cms/britannia/images/new/birmingham-exterior-carousel-1-660x340002.jpg"
}

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "hotelname" : "The Briar Rose",
    "description" : "Lively hotel with casual rooms & free Wi-Fi, plus a pub offering real ales & a steak menu.",
    "linkBook" : "https://www.google.com/travel/hotels/Birmingham/entity/CgsIgdTigN2fqOePARAB?g2lb=2502548%2C2503153%2C4254308%2C4258168%2C4260007%2C4270442%2C4271060%2C4274032%2C4291318%2C4305595%2C4306835%2C4308216%2C4314846%2C4317915%2C4328159%2C4329288%2C4330113%2C4338438%2C4348882%2C4270859%2C4284970%2C4291517%2C4292955%2C4316256&hl=en&gl=uk&un=1&q=hotels%20in%20birmingham%20city%20centre&rp=EIHU4oDdn6jnjwEQhcmA5c2dwMtmELbA85aS-NDZDBCTudPktszj7yE4AUAASAI&ictx=1&ved=2ahUKEwjGtNCbm9TnAhWMVBUIHdnLD3kQvS4wAHoECAgQIw&hrf=CgUIrwEQACIDR0JQKhYKBwjkDxACGBESBwjkDxACGBIYASgAWAGqARoKAgghEgIIDxICCBUSAggNEgIIZxICCC8YAaoBCgoCCBQSAggbGAGqAQ4KAggcEgIIcxICCEcYAaoBCgoCCCUSAgh6GAGqARoKAggREgIIKhICCEASAgg4EgIIVxICCCsYAaoBCwoCCC4SAwiAARgBqgEGCgIIRhgAqgEKCgIIUBICCE8YAaoBBgoCCDkYAJIBAiAB",
    "linkReview" : "https://www.google.com/travel/hotels/Birmingham/entity/CgsIgdTigN2fqOePARAB/reviews?g2lb=2502548%2C2503153%2C4254308%2C4258168%2C4260007%2C4270442%2C4271060%2C4274032%2C4291318%2C4305595%2C4306835%2C4308216%2C4314846%2C4317915%2C4328159%2C4329288%2C4330113%2C4338438%2C4348882%2C4270859%2C4284970%2C4291517%2C4292955%2C4316256&hl=en&gl=uk&un=1&q=hotels%20in%20birmingham%20city%20centre&rp=EIHU4oDdn6jnjwEQhcmA5c2dwMtmELbA85aS-NDZDBCTudPktszj7yE4AUAASAI&ictx=1&ved=2ahUKEwjGtNCbm9TnAhWMVBUIHdnLD3kQvS4wAHoECAgQIw&hrf=CgUIrwEQACIDR0JQKhYKBwjkDxACGBESBwjkDxACGBIYASgAWAGqARoKAgghEgIIDxICCBUSAggNEgIIZxICCC8YAaoBCgoCCBQSAggbGAGqAQ4KAggcEgIIcxICCEcYAaoBCgoCCCUSAgh6GAGqARoKAggREgIIKhICCEASAgg4EgIIVxICCCsYAaoBCwoCCC4SAwiAARgBqgEGCgIIRhgAqgEKCgIIUBICCE8YAaoBBgoCCDkYAJIBAiAB",
    "linkImage": "https://media-cdn.tripadvisor.com/media/photo-s/07/51/5d/57/the-briar-rose.jpg"
}


###
GET http://localhost:4000/login/wherethis

###
GET http://localhost:4000/login/testnewroute
