GET http://localhost:4000/

###

POST http://localhost:4000/hotel
Content-Type: application/json

{
    "hotelname" : "testnewroute",
    "description" : "Shan",
    "linkBook" : "scyws1",
    "linkReview" : "123456"
}

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "hotelname" : "wherethis",
    "description" : "Shan",
    "linkBook" : "scyws2",
    "linkReview" : "123457"
}


###
GET http://localhost:4000/hotel

###
GET http://localhost:4000/login/Premier
