GET http://localhost:4000/

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "firstname" : "Wenzheng",
    "lastname" : "Shan",
    "username" : "scyws1",
    "password" : "123456",
    "email" : "scyws1@nottingham.ac.uk",
    "phone" : "15653259955"
}

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "firstname" : "Steven",
    "lastname" : "Shan",
    "username" : "scyws2",
    "password" : "123457",
    "email" : "scyws2@nottingham.ac.uk",
    "phone" : "07529917457"
}

###
GET http://localhost:4000/foods/

###
GET http://localhost:4000/login/scyws2