
POST http://localhost:4000/register
Content-Type: application/json

{
    "firstname" : "Benjamin",
    "lastname" : "Smith",
    "username" : "psybjsm",
    "password" : "123456",
    "email" : "psybjsm@nottingham.ac.uk",
    "phone" : "15653259955"
}

###

GET http://localhost:4000/charity

###

DELETE http://localhost:4000/charity/5e9ae4f2c246892c647ebfcf
###

DELETE http://localhost:4000/charity/5e9ae28df6989a4fa4fc3e46

###

DELETE http://localhost:4000/charity/5e98647f3979ed3a888015d1

###

DELETE http://localhost:4000/charity/5e9864833979ed3a888015d2

###

DELETE http://localhost:4000/charity/5e9864873979ed3a888015d3

###

DELETE http://localhost:4000/charity/5e9981cdd0b4654420dbca8f

###

DELETE http://localhost:4000/charity/5e9981dcd0b4654420dbca90

###

DELETE http://localhost:4000/charity/5e9af283c246892c647ebfd3

###

DELETE http://localhost:4000/charity/5e9ada6339b845490c322214

###

DELETE http://localhost:4000/charity/5e9864763979ed3a888015d0

###

DELETE http://localhost:4000/charity/5e9af313c246892c647ebfd6

###



GET http://localhost:4000/charity/5e9af313c246892c647ebfd6

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 1,
    "charity_name" : "Birmingham Mind",
    "charity_phone" : "0121 262 3555",
    "charity_email" : "help@birminghammind.org",
    "charity_weblink" : "https://birminghammind.org/",
    "charity_introduce" : "Birmingham Mind is the largest independent mental health charity providing services in and beyond the City of Birmingham’s boundaries.",
    "charity_image" : "https://upload.wikimedia.org/wikipedia/en/0/01/Mind-logo.gif"
}

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 2,
    "charity_name" : "Breast Cancer Support charity",
    "charity_phone" : "0300 80 80 900",
    "charity_email" : "None",
    "charity_weblink" : "https://breastcancersupport.org.uk/",
    "charity_introduce" : "Breast Cancer Support is a UK charity",
    "charity_image" : "https://breastcancersupport.org.uk/wp-content/uploads/2015/11/logo.png"
}

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 3,
    "charity_name" : "Baren Davenport's Charity",
    "charity_phone" : "0121 236 8004",
    "charity_email" : "enquiries@barondavenportscharity.org",
    "charity_weblink" : "https://www.barondavenportscharity.org/",
    "charity_introduce" : "Established in 1930 the Charity provides grants in four categories. Applicants who meet the criteria can apply from this site.",
    "charity_image" : "https://www.barondavenportscharity.org/sites/all/themes/custom/nestor_subtheme/logo.png"
}

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 4,
    "charity_name" : "Cancer Research UK",
    "charity_phone" : "0300 123 1022 ",
    "charity_email" : "supporter.services@cancer.org.uk",
    "charity_weblink" : "https://www.cancerresearchuk.org/",
    "charity_introduce" : "We are the world’s largest charity dedicated to saving lives through research. Our vision is to bring forward the day when all cancers are cured.",
    "charity_image" : "https://www.cancerresearchuk.org/sites/all/themes/custom/cruk/cruk-logo.svg"
}

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 5,
    "charity_name" : "Heart Research UK Midlands",
    "charity_phone" : "0121 454 1799",
    "charity_email" : "midlands@heartresearch.org.uk",
    "charity_weblink" : "https://heartresearch.org.uk/contact-us/",
    "charity_introduce" : "We have a wonderful and dedicated team based in Birmingham.",
    "charity_image" : "https://www.thepayrollgivingteam.co.uk/wp/wp-content/uploads/2016/05/HRUK_Logo_Screen_FullColour-sml.jpg"
}

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 1,
    "charity_name" : "Baren Davenport's Charity",
    "charity_phone" : "0121 236 8004",
    "charity_email" : "enquiries@barondavenportscharity.org",
    "charity_weblink" : "https://www.barondavenportscharity.org/",
    "charity_introduce" : "Established in 1930 the Charity provides grants in four categories. Applicants who meet the criteria can apply from this site."
}

{
    "charityId" : 2,
    "charity_name" : "Birmingham Mind",
    "charity_phone" : "0121 236 8004",
    "charity_email" : "enquiries@barondavenportscharity.org",
    "charity_weblink" : "https://www.barondavenportscharity.org/",
    "charity_introduce" : "Established in 1930 the Charity provides grants in four categories. Applicants who meet the criteria can apply from this site."
}

{
    "charityId" : 3,
    "charity_name" : "Breast Cancer Support Charity",
    "charity_phone" : "0121 236 8004",
    "charity_email" : "enquiries@barondavenportscharity.org",
    "charity_weblink" : "https://www.barondavenportscharity.org/",
    "charity_introduce" : "Established in 1930 the Charity provides grants in four categories. Applicants who meet the criteria can apply from this site."
}

{
    "charityId" : 4,
    "charity_name" : "Cancer Research UK",
    "charity_phone" : "0121 236 8004",
    "charity_email" : "enquiries@barondavenportscharity.org",
    "charity_weblink" : "https://www.barondavenportscharity.org/",
    "charity_introduce" : "Established in 1930 the Charity provides grants in four categories. Applicants who meet the criteria can apply from this site."
}

{
    "charityId" : 5,
    "charity_name" : "Heart Research UK Midlands",
    "charity_phone" : "0121 236 8004",
    "charity_email" : "enquiries@barondavenportscharity.org",
    "charity_weblink" : "https://www.barondavenportscharity.org/",
    "charity_introduce" : "Established in 1930 the Charity provides grants in four categories. Applicants who meet the criteria can apply from this site."
}

###

GET http://localhost:4000/charity

###
//GET http://localhost:4000/login/scyws1

###
//GET http://localhost:4000/login/scyws2
