GET http://localhost:4000/

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "firstname" : "Benjamin",
    "lastname" : "Smith",
    "username" : "psybjsm",
    "password" : "123456",
    "email" : "psybjsm@nottingham.ac.uk",
    "phone" : "15653259955"
}

###

POST http://localhost:4000/charity
Content-Type: application/json

{
    "charityId" : 1,
    "charity_name" : "Baren Davenport's Charity",
    "charity_phone" : "",
    "charity_email" : "",
    "charity_weblink" : "",
    "charity_intro" : ""
}


###
GET http://localhost:4000/login/scyws1

###
GET http://localhost:4000/login/scyws2